service: test01a
frameworkVersion: "3"

plugins:
    - serverless-esbuild

provider:
    name: aws
    runtime: nodejs18.x
    stage: ${opt:stage, 'dev'}
    region: us-east-2
    environment:
        TEST01ATABLE_NAME: ${self:custom.Test01ATable.name}
    iam:
        role:
            statements:
                - ${file(iam/Test01ATableIAM.yml):Test01ATableIAM}
    httpApi:
        cors: true
    apiGateway:
        apiKeys:
            - user2

resources:
    Resources:
        Test01ATable: ${file(resources/Test01ATable.yml):Test01ATable}

functions:
    hello:
        handler: src/handlers/hello.handler
        events:
            - http:
                  method: POST
                  path: /hello
                  integration: lambda
                  private: true

custom:
    Test01ATable:
        name: !Ref Test01ATable
        arn: !GetAtt Test01ATable.Arn
