service: test01a
frameworkVersion: "3"

provider:
    name: aws
    runtime: nodejs18.x
    stage: ${opt:stage, 'dev'}
    region: us-east-2
    iam:
        role:
            statements:
                - Effect: "Allow"
                  Action:
                      - dynamodb:PutItem
                  Resource:
                      - arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/Test01ATable
    apiGateway:
        apiKeys:
            - user2

resources:
    Resources:
        Test01ATable:
            Type: AWS::DynamoDB::Table
            Properties:
                TableName: Test01ATable
                BillingMode: PAY_PER_REQUEST
                AttributeDefinitions:
                    - AttributeName: id
                      AttributeType: S
                KeySchema:
                    - AttributeName: id
                      KeyType: HASH

functions:
    hello:
        handler: src/handlers/hello.handler
        events:
            - http:
                  method: POST
                  path: /hello
                  integration: lambda
                  private: true
