service: sf-api-service
frameworkVersion: "3"

plugins:
    - serverless-esbuild

provider:
    name: aws
    runtime: nodejs18.x
    stage: ${opt:stage, 'dev'}
    region: us-east-2
    environment:
        TEST01ATABLE_NAME: ${self:custom.Test01ATable.name}
        MAIL_QUEUE_URL: ${self:custom.MailQueue.url}
    iam:
        role:
            statements:
                - ${file(iam/Test01ATableIAM.yml):Test01ATableIAM}
                - ${file(iam/MailQueueIAM.yml):MailQueueIAM}
    httpApi:
        cors: true
    apiGateway:
        apiKeys:
            - user2

resources:
    Resources:
        Test01ATable: ${file(resources/Test01ATable.yml):Test01ATable}

functions:
    hello:
        handler: src/handlers/hello.handler
        events:
            - http:
                  method: POST
                  path: /hello
                  integration: lambda
                  private: true

    cronjob:
        handler: src/handlers/cronJob.handler
        events:
            - schedule: rate(1 day)

custom:
    Test01ATable:
        name: !Ref Test01ATable
        arn: !GetAtt Test01ATable.Arn
    MailQueue:
        arn: ${cf:sf-send-email-service-${self:provider.stage}.MailQueueArn}
        url: ${cf:sf-send-email-service-${self:provider.stage}.MailQueueUrl}
