Test01ATable:
    Type: AWS::DynamoDB::Table
    Properties:
        TableName: SF-Test01ATable-${self:provider.stage}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
            - AttributeName: id
              AttributeType: S
        KeySchema:
            - AttributeName: id
              KeyType: HASH
